### ISSUE TITLE
A few small glitches

### ISSUE THREAD

**Issue by bradbulger** [AbhayPai/drupal9-starter#4]
Thanks for putting this together! I tried installing it, as a complete newb to Lando and Drupal9. The first problem was that there was no default.settings.php file. I copied the file from web/core/assets/scaffold/files/ to web/sites/default/ and that seemed to work OK. It also took some time to figure out the information I needed for the database configuration. The README mentions using lando info but it would be helpful to add it to the explicit Step list. Also, I didn't need to run 'lando composer install' after 'lando start'? It appears like it had already been done.

**Comment by bradbulger** [comment]
also, maybe there is some further step to install drush?

$ lando drush status
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "drush": executable file not found in $PATH: unknown

**Comment by AbhayPai** [comment]
Thanks a lot @bradbulger for using this repository and looking into some minor glitches.

Issue 1: `The first problem was that there was no default.settings.php file`
Answer: We do not need this default.settings.php in sites folder. According to the architecture we have placed for this version; we have kept  settings.php file intact inside the 'default' sites folder.

Issue 2: `Also, I didn't need to run 'lando composer install' after 'lando start'? `
Answer: Yes

Issue 3: `maybe there is some further step to install drush ?`
Answer: Yes, thanks for this request. Current master branch has drush inbuilt with this repository.

**Comment by bradbulger** [comment]
As to the default.settings.php file, the only reason I noticed was that install.php would not proceed with setting up the site without it. Maybe there is a more typical alternative method for the initial installation?

**Comment by AbhayPai** [comment]
Yes, I have updated readme.md file in master branch, you can refer to it.

**Comment by bradbulger** [comment]
Thanks!
